= API Xác thực Thông tin Cá nhân Người dùng từ (CMND/CCCD)
Tác giả <hoangll@vissoft>
v1.0, {docdate}
:toc:
:toc-title: Mục lục
:sectnums:

== Mô tả API
API này được sử dụng để xác minh thông tin cá nhân của người dùng được trích xuất từ ảnh mặt trước, mặt sau của CCCD và ảnh chân dung. API này sử dụng phương thức POST và trả về kết quả dưới dạng JSON.

== Thiết kế API

=== Request

.Endpoint
[source]
----
POST /customer-service/private/v1/subscribers
----

RequestPart
|===
|Key |Value

|front_img
|MultipartFile

|back_img
|MultipartFile

|portrait_img
|MultipartFile
|===

=== Response
Kết quả trả về là các trường có trên màn hình và tên các trường trong Body được định nghĩa theo kết quả trả về của API OCR

.Success Response (200 OK)
[source,json]
----
{
  "document": "loại giấy tờ",
  "name": "họ và tên",
  "id": "số giấy tờ",
  "issue_by": "nơi cấp",
  "issue_date": "Ngày cấp",
  "birthday": "Ngày sinh",
  "sex": "giới tính",
  "address": "Địa chỉ thường trú",
  "city": "Tỉnh/Thành phố (đang thiếu trong API OCR)",
  "district": "Quận/Huyện",
  "ward": "Phuờng/Xã (đang thiếu trong API OCR)",
  "expiry": "ngày hết hạn"
}
----

.Error Response
[source,json]
----
{
  "message": "Image size larger than 500kb",
  "code": "001"
}
----

=== Tổ chức Class
|===
|Các Class

|SubscriberController

|SubscriberService

|SubscriberServiceImpl

|PersonalInfoDTO

|OCRInfoResponse

|EKYCResponse

|C06Response

|BaseMapper

|MinIOConfig

|S3Service

|S3ServiceImpl
|===

=== Sequence Diagram

[plantuml, diagram1, png]
----
@startuml
autonumber

actor User
participant "Customer Service" as CS
database "VIS-Schema" as DB

User -> CS: Upload ảnh căn cước mặt trước, mặt sau, ảnh chân dung
CS -> CS: Kiểm tra dung lượng ảnh
alt Dung lượng > 500kb
    CS -> User: Báo lỗi "Dung lượng ảnh quá lớn"
end

CS -> CS: Gọi API OCR

alt Có vi phạm tiêu chí
    CS -> User: Báo lỗi "Vi phạm tiêu chí"
end

CS -> CS: Thực hiện validate theo 8 tiêu chí
alt Có vi phạm tiêu chí
    CS -> User: Báo lỗi "Vi phạm tiêu chí"
end

CS -> CS: Gọi API C06

alt Thông tin không chính xác
    CS -> User: Báo lỗi thông tin không chính xác
else Thông tin chính xác
    CS -> User: Thông tin chính xác
end

CS -> CS: Gọi API EKYC
alt Ảnh có tỷ lệ khớp quá thấp
    CS -> User: Báo lỗi ảnh không chính xác
end
CS -> User: Trả về thông tin đã trích xuất

@enduml
----

